### ISSUE TITLE
Miscs discussion

### ISSUE THREAD

**Issue by Carreau** [ipython/sloan-2013-reports#2]
- JakeVDP is now Director of Research at eScience Institut of UW
- senseplatform.com now also use IPython (not our protocol, not notebook though)
- preview.python.org use an IPython Shell :-)

**Comment by Carreau** [comment]
Gallery can be editted by user (I think it is worth mentioning it) as the number of edit is mainly done by non-IPython dev

**Comment by fperez** [comment]
All done, thanks!
